# Generated by Selenium IDE
import time
from selenium import webdriver
from selenium.webdriver.common.by import By


class TestMytest1:
    def setup_method(self, method):
        self.driver = webdriver.Chrome()
        self.vars = {}

    def teardown_method(self, method):
        self.driver.quit()

    def wait_for_window(self, timeout=2):
        time.sleep(round(timeout / 1000))
        wh_now = self.driver.window_handles
        wh_then = self.vars["window_handles"]
        if len(wh_now) > len(wh_then):
            return set(wh_now).difference(set(wh_then)).pop()

    def test_mytest1(self):
        self.driver.get("https://trytestingthis.netlify.app/")
        self.driver.set_window_size(1111, 583)
        self.driver.find_element(By.ID, "fname").click()
        self.driver.find_element(By.ID, "fname").send_keys("maria")
        self.driver.find_element(By.ID, "lname").send_keys("layane")
        self.driver.find_element(By.CSS_SELECTOR, "label:nth-child(17)").click()
        self.driver.find_element(By.ID, "a").send_keys("100")
        self.driver.find_element(By.ID, "a").click()
        self.driver.find_element(By.CSS_SELECTOR, "fieldset:nth-child(1)").click()
        self.driver.find_element(By.ID, "favcolor").click()
        self.driver.find_element(By.ID, "favcolor").send_keys("#ffffff")
        self.driver.find_element(By.CSS_SELECTOR, "fieldset:nth-child(1)").click()
        self.driver.find_element(By.NAME, "message").click()
        self.driver.find_element(By.NAME, "message").click()
        self.driver.find_element(By.NAME, "message").send_keys("The cat was playing in the garden.\\nabc")
        self.vars["window_handles"] = self.driver.window_handles
        self.driver.find_element(By.XPATH, "//fieldset/button").click()
        self.vars["win6713"] = self.wait_for_window(2000)
        self.vars["root"] = self.driver.current_window_handle
        self.driver.switch_to.window(self.vars["win6713"])
        self.driver.switch_to.window(self.vars["root"])
        self.driver.find_element(By.ID, "uname").click()
        self.driver.find_element(By.ID, "uname").send_keys("test")
        self.driver.find_element(By.ID, "pwd").send_keys("test")
        self.driver.find_element(By.CSS_SELECTOR, "input:nth-child(10)").click()
        self.driver.find_element(By.CSS_SELECTOR, ".main").click()
